CREATE TABLE IF NOT EXISTS LISTS
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME TEXT                              NOT NULL
);

CREATE TABLE IF NOT EXISTS TASKS
(
    ID      INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME    TEXT                              NOT NULL,
    LIST_ID INTEGER                           NOT NULL,
    DONE    VARCHAR(1) DEFAULT 'F',
    FOREIGN KEY (LIST_ID)
        REFERENCES LISTS (ID)
);